
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginCo.java
 *
 * Created on Mar 6, 2012, 6:00:30 PM
 */
/**
 *
 * @author portgas
 */
public class LoginCo extends javax.swing.JFrame {
    private String tgl;
    private String day;
    private String MM;
    private String day2;
    private String bulan1;
    private int iBulan;
    private String bulan2;

    /** Creates new form LoginCo */
    public LoginCo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JTextField();
        Date1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JTextField();
        Date2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        Zco = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Zcw = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Halo = new javax.swing.JTextArea();
        Hasil = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data laki-laki");

        jLabel2.setText("Nama :");

        jLabel3.setText("Tanggal Lahir :");

        Date1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Date1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nama1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ramal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Simpan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel4.setText("Data perempuan");

        jLabel5.setText("Nama :");

        jLabel6.setText("Tanggal Lahir :");

        Nama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama2ActionPerformed(evt);
            }
        });

        Date2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Date2PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nama2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        Zco.setText("Zodiak Laki-laki");

        jPanel5.setLayout(new java.awt.CardLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aquarius.jpg"))); // NOI18N
        jPanel5.add(jLabel7, "Aquarius");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aries.jpg"))); // NOI18N
        jPanel5.add(jLabel8, "Aries");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancer.jpg"))); // NOI18N
        jPanel5.add(jLabel9, "Cencer");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capricorn.jpg"))); // NOI18N
        jPanel5.add(jLabel10, "Capricon");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gemini.jpg"))); // NOI18N
        jPanel5.add(jLabel11, "Gemini");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leo.jpg"))); // NOI18N
        jPanel5.add(jLabel12, "Leo");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libra.jpg"))); // NOI18N
        jPanel5.add(jLabel13, "Libra");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pisces.jpg"))); // NOI18N
        jPanel5.add(jLabel14, "Pisces");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sagitarius.jpg"))); // NOI18N
        jPanel5.add(jLabel15, "Sagitarius");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scorpio.jpg"))); // NOI18N
        jPanel5.add(jLabel16, "Scorpio");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taurus.jpg"))); // NOI18N
        jPanel5.add(jLabel17, "Taurus");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virgo.jpg"))); // NOI18N
        jPanel5.add(jLabel18, "Virgo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Zco))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Zco)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));

        Zcw.setText("Zodiak Perempuan");

        jPanel7.setLayout(new java.awt.CardLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aquarius.jpg"))); // NOI18N
        jPanel7.add(jLabel19, "Aquarius2");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aries.jpg"))); // NOI18N
        jPanel7.add(jLabel20, "Aries2");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancer.jpg"))); // NOI18N
        jPanel7.add(jLabel21, "Cancer2");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capricorn.jpg"))); // NOI18N
        jPanel7.add(jLabel22, "Capricon2");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gemini.jpg"))); // NOI18N
        jPanel7.add(jLabel23, "Gemini2");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leo.jpg"))); // NOI18N
        jPanel7.add(jLabel24, "Leo2");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libra.jpg"))); // NOI18N
        jPanel7.add(jLabel25, "Libra2");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pisces.jpg"))); // NOI18N
        jPanel7.add(jLabel26, "Pisces2");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sagitarius.jpg"))); // NOI18N
        jPanel7.add(jLabel27, "Sagitarius2");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scorpio.jpg"))); // NOI18N
        jPanel7.add(jLabel28, "Scorpio2");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taurus.jpg"))); // NOI18N
        jPanel7.add(jLabel29, "Taurus2");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virgo.jpg"))); // NOI18N
        jPanel7.add(jLabel30, "Virgo2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Zcw)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Zcw)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        Halo.setColumns(20);
        Halo.setRows(5);
        jScrollPane1.setViewportView(Halo);

        Hasil.setText("j");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Hasil)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void Nama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama2ActionPerformed
 // TODO add your handling code here:
}//GEN-LAST:event_Nama2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Nama1.setText("");
Nama2.setText("");
Date1.setDate(null);
Date2.setDate(null);
Hasil.setText("");
Halo.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (Nama1.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Eror: Anda belum memasukan nama", "Eror: Anda belum memasukan nama", JOptionPane.WARNING_MESSAGE);
}
    if (Nama2.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Eror: Anda belum memasukan nama", "Eror: Anda belum memasukan nama", JOptionPane.WARNING_MESSAGE);

    }
 if (Date1.getDate()==null){
    JOptionPane.showMessageDialog(null, "Eror: Anda belum memasukan tanggal lahir", "Eror: Anda belum memasukan nama", JOptionPane.WARNING_MESSAGE);
 }
 int tahun1 = Integer.parseInt(day.substring(7,11));
 int hari1 = Integer.parseInt(day.substring(0,2));
 bulan1 = (String) day.substring(3,6);

 //zodiak pria
 Integer nilai1;
 if(bulan1.compareTo("Jan")== 0){
 if(hari1 >= 20){
         Zco.setText("Aquarius");
          CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Aquarius");
        nilai1=10;
     }
     else{
         Zco.setText("Capricorn");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Capricon");
     nilai1=15;
     }
 }
 if(bulan1.compareTo("Feb")== 0){
if(hari1 >= 19){
         Zco.setText("Pisces");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Pisces");
        nilai1=20;
     }
     else{
         Zco.setText("Aquarius");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Aquarius");
        nilai1=25;
     }
 }
 if(bulan1.compareTo("Mar")== 0){
    if(hari1 >= 21){
         Zco.setText("Aries");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Aries");
        nilai1=30;
     }
     else{
         Zco.setText("Pisces");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Pisces");
        nilai1=35;
     }
 }
 if(bulan1.compareTo("Apr")== 0){
    if(hari1 >= 20){
         Zco.setText("Taurus");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Taurus");
        nilai1=40;
     }
     else{
         Zco.setText("Aries");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Aries");
        nilai1=45;
     }
 }
 if(bulan1.compareTo("May")== 0){
    if(hari1 >= 21){
         Zco.setText("Gemini");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Gemini");
        nilai1=50;
     }
     else{
         Zco.setText("Taurus");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Taurus");
        nilai1=10;
     }
 }
 if(bulan1.compareTo("Jun")== 0){
    if(hari1 >= 21){
         Zco.setText("Cancer");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Cencer");
        nilai1=15;
     }
     else{
         Zco.setText("Gemini");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Gemini");
        nilai1=20;
     }
 }
 if(bulan1.compareTo("Jul")== 0){
    if(hari1 >= 23){
         Zco.setText("Leo");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Leo");
        nilai1=25;
     }
    else{
         Zco.setText("Cancer");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Cencer");
        nilai1=30;
     }
 }
 if(bulan1.compareTo("Aug")== 0){
    if(hari1 >= 23){
         Zco.setText("Virgo");
CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Virgo");
        nilai1=35;
    }
     else{
         Zco.setText("Leo");
    CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Leo"); 
        nilai1=40;
    }
 }
 if(bulan1.compareTo("Sep")== 0){
    if(hari1 >= 23){
         Zco.setText("Libra");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Libra");
        nilai1=45;
     }
     else{
         Zco.setText("Virgo");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Virgo");
        nilai1=50;
     }
 }
 if(bulan1.compareTo("Oct")== 0){
    if(hari1 >= 23){
         Zco.setText("Scorpio");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Scorpio");
        nilai1=10;
     }
     else{
         Zco.setText("Libra");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Libra");
        nilai1=15;
     }
 }
 if(bulan1.compareTo("Nov") == 0){
    if(hari1 >= 22){
         Zco.setText("Sagitarius");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Sagitarius");
        nilai1=20;
     }
     else{
         Zco.setText("Scorpio");
         CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Scorpio");
        nilai1=25;
     }   
 }else {
if(hari1 >= 22){
         Zco.setText("Capricon");
        CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Capricon");
        nilai1=30;
     }
     else{
         Zco.setText("Sagitarius");
        CardLayout cl = (CardLayout) (jPanel5.getLayout());
        cl.show(jPanel5, "Sagitarius");
        nilai1=35;
     } 
} 
 //Zodiak Perempuan
 Integer nilai2;
 int tahun2 = Integer.parseInt(day2.substring(7,11));
 int hari2 = Integer.parseInt(day2.substring(0,2));
 bulan2 = (String) day2.substring(3,6);
 if(bulan2.compareTo("Jan")== 0){
 if(hari2 >= 20){
         Zcw.setText("Aquarius");
          CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Aquarius2");
        nilai2=10;
     }
     else{
         Zcw.setText("Capricorn");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Capricon2");
     nilai2=15;
     }
 }
 if(bulan2.compareTo("Feb")== 0){
if(hari2 >= 19){
         Zcw.setText("Pisces");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Pisces2");
        nilai2=20;
     }
     else{
         Zcw.setText("Aquarius");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Aquarius2");
        nilai2=25;
     }
 }
 if(bulan2.compareTo("Mar")== 0){
    if(hari2 >= 21){
         Zcw.setText("Aries");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Aries2");
        nilai2=30;
     }
     else{
         Zcw.setText("Pisces");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Pisces2");
        nilai2=35;
     }
 }
 if(bulan2.compareTo("Apr")== 0){
    if(hari2 >= 20){
         Zcw.setText("Taurus");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Taurus2");
        nilai2=40;
     }
     else{
         Zcw.setText("Aries");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Aries2");
        nilai2=45;
     }
 }
 if(bulan2.compareTo("May")== 0){
    if(hari2 >= 21){
         Zcw.setText("Gemini");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Gemini2");
        nilai2=50;
     }
     else{
         Zcw.setText("Taurus");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Taurus");
        nilai2=10;
     }
 }
 if(bulan2.compareTo("Jun")== 0){
    if(hari2 >= 21){
         Zcw.setText("Cancer");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Cancer2");
        nilai2=15;
     }
     else{
         Zcw.setText("Gemini");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Gemini2");
        nilai2=20;
     }
 }
 if(bulan2.compareTo("Jul")== 0){
    if(hari2 >= 23){
         Zcw.setText("Leo");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Leo2");
        nilai2=25;
     }
    else{
         Zcw.setText("Cancer");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Cancer2");
        nilai2=30;
     }
 }
 if(bulan2.compareTo("Aug")== 0){
    if(hari2 >= 23){
         Zcw.setText("Virgo");
CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Virgo2");
        nilai2=35;
    }
     else{
         Zcw.setText("Leo");
    CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Leo2"); 
        nilai2=40;
    }
 }
 if(bulan2.compareTo("Sep")== 0){
    if(hari2 >= 23){
         Zcw.setText("Libra");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Libra2");
        nilai2=45;
     }
     else{
         Zcw.setText("Virgo");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Virgo2");
        nilai2=50;
     }
 }
 if(bulan2.compareTo("Oct")== 0){
    if(hari2 >= 23){
         Zcw.setText("Scorpio");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Scorpio2");
        nilai2=10;
     }
     else{
         Zcw.setText("Libra");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Libra2");
        nilai2=15;
     }
 }
 if(bulan2.compareTo("Nov") == 0){
    if(hari2 >= 22){
         Zcw.setText("Sagitarius");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Sagitarius2");
        nilai2=20;
     }
     else{
         Zcw.setText("Scorpio");
         CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Scorpio2");
        nilai2=25;
     }   
 }else {
if(hari2 >= 22){
         Zcw.setText("Capricon");
        CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Capricon2");
        nilai2=30;
     }
     else{
         Zcw.setText("Sagitarius");
        CardLayout cl = (CardLayout) (jPanel7.getLayout());
        cl.show(jPanel7, "Sagitarius2");
        nilai2=35;
     } 
}
Integer hasil = nilai1 +nilai2;
Hasil.setText(hasil+"%");
        if (hasil >= 80){
             Halo.setText("Haloo "+ Nama1.getText()  +" dan "+ Nama2.getText()+ 
 '\n' + "Kali ini saya ingin mencoba meramal tentang kecocokan hubungan kalian berdasarkan zodiak."+
                      '\n' + "Selamat kalian mempunyai presentasi kecocokan yang tinggi."+
                     '\n' + "Dalam hubungan kalian, kalian mempunyai sifat yang saling melengkapi,"+
                     '\n' + "walau kadang kalian sering bertengkar, tapi semua itu didasarkan rasa sayang"+
                     '\n' + "JADI PERTAHANKAN HUBUNGAN KALIAN....");             
        }
         if (hasil >=45){
               Halo.setText("Haloo "+ Nama1.getText()  +" dan "+ Nama2.getText()+ 
                        '\n' + "Kali ini saya ingin mencoba meramal tentang kecocokan hubungan kalian berdasarkan zodiak."+
                      '\n' + "Kalian mempunyai presentasi kecocokan yang agak kurang bagus nih."+
                     '\n' + "Dalam hubungan kalian, kalian mempunyai sifat yang saling melengkapi,"+
                     '\n' + "walau kadang kalian sering bertengkar, tapi semua itu didasarkan rasa sayang"+
                     '\n' + "JADI PERTAHANKAN HUBUNGAN KALIAN....");      
         }
         else{
              Halo.setText("Haloo "+ Nama1.getText()  +" dan "+ Nama2.getText()+ 
                        '\n' + "Kali ini saya ingin mencoba meramal tentang kecocokan hubungan kalian berdasarkan zodiak."+
                      '\n' + "Kalian mempunyai presentasi kecocokan yang sangat buruk,"+
                      '\n' + "kayanya lebih baik putus aja, dari pada pacaran ribut terus.");  
         }
}//GEN-LAST:event_jButton2ActionPerformed

private void Date1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Date1PropertyChange
try{
    if(Date1.getDate()!=null){
        String tampilan = "dd MMM yyyy";
SimpleDateFormat format = new SimpleDateFormat(tampilan);
day  =
        String.valueOf( format.format(Date1.getDate()));
    }
}catch(Exception e){}

}//GEN-LAST:event_Date1PropertyChange

private void Date2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Date2PropertyChange
try{
    if(Date2.getDate()!=null){
        String tampilan2 = "dd MMM yyyy";
SimpleDateFormat format = new SimpleDateFormat(tampilan2);
day2  =
        String.valueOf( format.format(Date2.getDate()));
    }
}catch(Exception e){}
}//GEN-LAST:event_Date2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginCo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date1;
    private com.toedter.calendar.JDateChooser Date2;
    private javax.swing.JTextArea Halo;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField Nama1;
    private javax.swing.JTextField Nama2;
    private javax.swing.JLabel Zco;
    private javax.swing.JLabel Zcw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
